language: node_js
node_js:
- node
script:
- npm run lint
- npm test
addons:
  code_climate:
    repo_token: b6f2693e7cfd15d420d635a9cdee642df1829ccf66fc6a66a30d6e8f2a0b9003
  browserstack:
    username: "gregorybeaver1"
    access_key:
      secure: "xiqQi/vfYMDTCocRW0gSpoZLJR0nt+YVkxkwK9VTDvxJNWjKZ4UwBL8SukVE12JeQ/9IzpGwYeCXFkUl7tuEW5OcQmS6E/oPoDsxbKu0nebWzA3WWByTZGmTMyg2hziYIEsXvV4lYkliSfOxtssrjcgXl8vJXBgBXCHebEshZ5h4n6qnULPumpqHvb0cs5j+fhuHBo5u/Kk7f82LjYyhVYrsTxEIx7ippszlKYr3pX9MhCuaCAnimQO1ki787YcIqFQYfFlffFl5L13kNSkCIsgyblOwuC1MclgXLerfgaDAMfSTCP1haFfvmDmVpGPoHCX8rwLg2KsJPNRb7tG34C4MFkA/nzbFRiaN/vul791wGPNYJzfl91uNxflIsMkajX5SQNaM3BOCxaC8JBgICfNLer8qkb19qAHrEJw+J/FK+2FTg/jOjFCL4U7ZnTxvkG0Mja5LG9iZjZu1vxGhRSchGhmPJLLQ+7dyJfbLchqR4iTjxa2iddy3lUrn3Sjq9WZiVAlSrxZlLAHLnJItfjAiGTX1rjXx55xTIwlvJxsLnJxexf7V3P0mvYMr1yO9p9oi4ZsXXhYRX/t4t55nT5rPbaoNl69bfZ945gKeLZ8U5vwksMESSn0QXj8xJbqRnCPUoWPuRkCJE26cduVTv1g391laU9x/dmBONL1Vb9I="
env:
  global:
  - BS_AUTOMATE_PROJECT="$TRAVIS_REPO_SLUG"
  - BS_AUTOMATE_BUILD="Travis build No. $TRAVIS_BUILD_NUMBER for $TRAVIS_REPO_SLUG"
