export const CREATE_ROUTE = '@@react-redux-saga-router/CREATE_ROUTE'
export const EDIT_ROUTE = '@@react-redux-saga-router/EDIT_ROUTE'
export const REMOVE_ROUTE = '@@react-redux-saga-router/REMOVE_ROUTE'
export const ACTION = '@@react-redux-saga-router/ACTION'
export const ROUTE = '@@react-redux-saga-router/ROUTE'
export const MATCH_ROUTES = '@@react-redux-saga-router/MATCH_ROUTES'
export const SET_PARAMS = '@@react-redux-saga-router/SET_PARAMS'
